### ISSUE TITLE
Please upgrade to latest version of Vue3 and Inertia and Laravel. 

### ISSUE THREAD

**Issue by bhojkamal** [inertiajs/pingcrm#163]
Hello, 

Could you please upgrade to the latest Vue 3. Vue 3 is already out for long time. So, please upgrade to the latest version of all 3, Vue 3, Laravel and Inertia. 

Thanks.

**Comment by sluxzer** [comment]
Would be love to see this change.

**Comment by EnnioSimoes** [comment]
I would like to see this upgrade too

**Comment by SaeedSoltoon** [comment]
I would like to see this upgrade too

**Comment by michaelkorshun** [comment]
I would like to see this upgrade too

**Comment by claudiodekker** [comment]
Hey all,

I just wanted to let you know that your request has been heard loud and clear, and that we do intend to pick this up at some point. The reason we're not doing so right now, is because this would mean we'd be spending time on this instead of on Inertia itself, which would be kind of pointless, as once the Dialogs feature gets released this would mean another update/rewrite of this repository. So, instead, we intend to do this at some point _after_ that feature is done. Thanks!
