### ISSUE TITLE
Reduce time to load

### ISSUE THREAD

**Issue by connecteev** [inertiajs/pingcrm#33]
Installed both https://github.com/reinink/client-side-rendering-in-laravel and https://github.com/inertiajs/pingcrm
and it turns out pingcrm (built on infinityjs) is a lot slower to load each page.
Why is that and is it possible to make infiniteyjs / pingcrm as snappy as the client-side-rendering-in-laravel codebase?

**Comment by sebastiandedeyne** [comment]
I just installed both side by side, and here are my findings. 

I followed the exact installation instructions, with some exceptions: 

- I ran `npm run production` instead of `npm run dev`, because it's a better baseline to compare performance
- I used a MySQL database in PingCRM to have the comparable speeds on the server
- I set `APP_DEBUG` to false

I'm not noticing any difference between the two. Could you be a bit more specific? Did you compare server response times? Are you talking about the initial load, or subsequent loads? Maybe provide a video that showcases the difference.

Also note that this isn't really a 100% fair comparison: PingCRM uses a much larger dataset, and has a lot more going on when it comes to styling and components on the page. This won't make a noticable difference, but there will be a few milliseconds difference between the two.

Going to close this, but feel free to ping back with further questions, or discuss this further on [Discord](https://twitter.com/reinink/status/1149697245891055620)!
