### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by soundar2** [inertiajs/pingcrm#49]
I followed instructions to the letter. I just get a blank page when I navigate to index.php

**Comment by Juhlinus** [comment]
Hello, @soundar2 !

Did you copy the .env file?

Could you show what it looks like, if you did.

**Comment by sebastiandedeyne** [comment]
Are there any console errors?

**Comment by zarkoAtanasov** [comment]
Hello,

I'm having the same issue. 
No errors in the console, no issues in the network.  

I downgraded the laravel-mix version because I had some issues during the compilation.
Followed the docs and I'm still thinking that I missed something.

This is what I have:

`resources/app.js`
```js
Vue.use(InertiaApp);

const app = document.getElementById('app')

new Vue({
    render: h => h(InertiaApp, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => import(`./Pages/${name}`).then(module => module.default),
        },
    }),
}).$mount(app)
```
`routes/web.php`

```php
use Inertia\Inertia;
Route::get('/', function () {
    return Inertia::render('Home/Welcome');
    // return view('welcome');
});
```

`resources/js/Pages/Home/Welcome.vue`
```js
<template>
  <div>
    <h1>Simple Hello test</h1>
  </div>
</template>

<script>
export default {
  name: "Welcome"
};
</script>
```

And the only thing that I get when I navigate to this route is:

![image](https://user-images.githubusercontent.com/18619738/67124762-e5713e00-f1fb-11e9-99d0-1103752335d2.png)

Vue Devtools:
![image](https://user-images.githubusercontent.com/18619738/67124819-06399380-f1fc-11e9-88a5-12444c89cb9b.png)

I am not quite sure that the OS version and server version are important but anyway:

**Vagrant/Homestead-7** (Not pretty sure about the version)
**Laravel: Framework: 6.3.0**

I hope this info could help.

**Comment by Juhlinus** [comment]
Hello @zarkoAtanasov !

Are you using the @inertia blade helper in your `app.blade.php`?

**Comment by zarkoAtanasov** [comment]
Hello, @Juhlinus 
Yes, I use `@inertia` directive, I forgot to mention that.
Also I tried to use 
`<div id="app" data-component="{{$component}}" data-props={{json_encode($props)}}>`
(as it defined in the laravel directive)

But as I expected, I got an `Undefined variable $component` error.

**Comment by Juhlinus** [comment]
Could you change your `resources/js/app.js` so it looks like this?

```javascript
import { InertiaApp } from '@inertiajs/inertia-vue'
import Vue from 'vue'

Vue.use(InertiaApp)

const app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => require(`./Pages/${name}`).default,
    },
  }),
}).$mount(app)
```

**Comment by zarkoAtanasov** [comment]
Hello, @Juhlinus 

I changed it like you said and it doesn't work. 
I tried one more thing:
Instead of `require('./Pages/${name}').default` 
I used 
`require('./Pages/${name}')`
and it works. (simply remove `.default`). 

So now I can use either
`resolveComponent: name => require('./Pages/${name}')` 
or 
`resolveComponent: name => import('./Pages/${name}')`

I am not sure why this was the reason but it works now. 

Thanks for your response!

**Comment by sebastiandedeyne** [comment]
For anyone having the same problem and looking for an explanation…

> I downgraded the laravel-mix version because I had some issues during the compilation

`require` works differently in older versions of Webpack. In Laravel Mix `< 4.0` you need to emit the `.default` from `require` calls.

**Comment by reinink** [comment]
Awesome, glad you got it figured out. 👍

**Comment by SOHELAHMED7** [comment]
Note :
if above solution does not work, try

1. delete node_modules folder
2. `$ npm install`
3. `$ php artisan serve --port=8080`

**Comment by kadusalles** [comment]
I just change from import to require

> Hello, @Juhlinus
> 
> I changed it like you said and it doesn't work.
> I tried one more thing:
> Instead of `require('./Pages/${name}').default`
> I used
> `require('./Pages/${name}')`
> and it works. (simply remove `.default`).
> 
> So now I can use either
> `resolveComponent: name => require('./Pages/${name}')`
> or
> `resolveComponent: name => import('./Pages/${name}')`
> 
> I am not sure why this was the reason but it works now.
> 
> Thanks for your response!

I just change from import to require and it works ( i change to import because a step of code spliting in the tutorial, i think i dont understand it well )

**Comment by mojtabasji** [comment]
I had same problem in laravel.
When I upload projects on host I just seen blank pages without any error.
I finally  found where is the problem.😃
I first created laravel project with cpanel tools and then over write some changed file and folders. In this way i overwrite `vendor/autoload.php` File that inside that use another file and function that functions name isn’t unique. I find that and replace that in autoload.php then its works successfully.
