### ISSUE TITLE
How to change the panigation window "onEachSide(5)"

### ISSUE THREAD

**Issue by thamibn** [inertiajs/pingcrm#83]
Please help on how can i customise the pagination to show 5 links befor the "..." curretly is showing 10 links.

if i add the ->onEachSide(5) it add it on top of the default 10 links and make it 15 links before "..." .

**Comment by reinink** [comment]
Not sure...I have never done this. I don't think the Laravel pagination even provides options around this. In Laravel this is controlled by the `UrlWindow` class, and I don't see any options for controlling the number of links. Sorry I cannot be more helpful, but since question is outside of the scope of Inertia.js and Ping CRM, I am going to close this. Good luck!
