### ISSUE TITLE
Registering new route 

### ISSUE THREAD

**Issue by Mellaoui** [inertiajs/pingcrm#95]
I am not able to register a new route it keeps redirecting to the login page  while I want to have a landing page in  URL ('/')
any solution, please?

**Comment by tonjohn** [comment]
Can you share what the code in your routes/web.php looks like? It sounds like route requires authentication.

PingCRM is setup so that the root route ('/') uses the auth middleware, requiring the user to be authenticated to view:

```php
Route::get('/', [DashboardController::class, 'index'])
    ->name('dashboard')
    ->middleware('auth');
```

If you want the page to be viewable without being logged in, remove the auth middleware from the route:
```php
Route::get('/', [DashboardController::class, 'index'])
    ->name('dashboard')
```

**Comment by reinink** [comment]
Thanks for jumping in here @tonjohn. 👍 

Closing this, given the lack of response.
